# lnmp
version: '3'

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/mysql_sock:/var/run/mysqld
      - ./mysql/var/lib/mysql-files:/var/lib/mysql-files
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
    networks:
      - lnmp

  redis:
    image: redis:5
    container_name: redis
    hostname: redis
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - lnmp

  php:
    build: ./php74
    container_name: php
    hostname: php
    restart: always
    ports:
      - "9000:9000"
    links:
      - mysql:mysql
      - redis:redis
    volumes:
      - /data/wwwroot:/data/webapp
      - ./logs/web/php-fpm.log:/var/log/fpm-php.www.log
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
    networks:
      - lnmp

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/wwwroot:/data/webapp
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
      - ./nginx/run/nginx.pid:/var/run/nginx.pid
    links:
      - php:PHP-FPM
    networks:
      - lnmp

  mongo:
    image: mongo:3
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./mongo/data:/data/db
      - ./logs/mongo/mongod.log:/var/log/mongodb/mongod.log
      - ./mongo/conf/mongod.conf:/etc/mongod.conf
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123123
    networks:
      - lnmp

networks:
  lnmp:
    driver: bridge